export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR="REGISTER_USER_ERROR"

export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"

export const GET_USER_PROFILE_REQUEST="GET_USER_PROFILE_REQUEST"
export const GET_USER_PROFILE_SUCCESS="GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAIL="GET_USER_PROFILE_FAIL"

export const GET_DIET_PLANS_REQUEST="GET_DIET_PLANS_REQUEST"
export const GET_DIET_PLANS_SUCCESS="GET_DIET_PLANS_SUCCESS"
export const GET_DIET_PLANS_FAIL="GET_DIET_PLANS_FAIL"

export const GET_MEDICATION_REQUEST = "GET_MEDICATION_REQUEST";
export const GET_MEDICATION_SUCCESS = "GET_MEDICATION_SUCCESS";
export const GET_MEDICATION_FAIL = "GET_MEDICATION_FAIL";

export const GET_LABS_REQUEST = "GET_LABS_REQUEST";
export const GET_LABS_SUCCESS = "GET_LABS_SUCCESS";
export const GET_LABS_FAIL = "GET_LABS_FAIL";

export const GET_USER_MED_RECORDS_REQUEST="GET_USER_MED_RECORDS_REQUEST"
export const GET_USER_MED_RECORDS_SUCCESS="GET_USER_MED_RECORDS_SUCCESS"
export const GET_USER_MED_RECORDS_FAIL="GET_USER_MED_RECORDS_FAIL"

export const ADD_USER_MED_RECORD_REQUEST="ADD_USER_MED_RECORD_REQUEST"
export const ADD_USER_MED_RECORD_SUCCESS="ADD_USER_MED_RECORD_SUCCESS"
export const ADD_USER_MED_RECORD_FAIL="ADD_USER_MED_RECORD_FAIL"

export const GET_USER_PRESCRIPTIONS_REQUEST="GET_USER_PRESCRIPTIONS_REQUEST"
export const GET_USER_PRESCRIPTIONS_SUCCESS="GET_USER_PRESCRIPTIONS_SUCCESS"
export const GET_USER_PRESCRIPTIONS_FAIL="GET_USER_PRESCRIPTIONS_FAIL"